import { describe, expect, test, beforeAll } from 'bun:test'
import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { initSync, encrypt_chunk, decrypt_chunk } from 'beebeeb-wasm'
import { encryptThumbnailBlob, decryptThumbnailBlob } from '../src/lib/thumbnail'

// ─── Cross-client thumbnail-encryption KAT (K3, task 1383) ─────────────────
//
// web's thumbnail.ts (encryptThumbnailBlob / decryptThumbnailBlob — the
// latter extracted here from what used to be duplicated inline in
// fetchAndDecryptThumbnail/fetchAndDecryptLargeThumbnail, K3) implements
// AES-256-GCM directly via WebCrypto, independently of core. Wire format:
// nonce(12) || AES-256-GCM-ciphertext, no AAD, raw 32-byte FileKey (no KDF),
// over arbitrary-length plaintext — the exact format
// `beebeeb-core::encrypt::encrypt_chunk`/`decrypt_chunk` produce. The pinned
// vector lives at `repos/core/test-vectors/vectors.json` (name
// `thumbnail_encrypt`), generated by
// `repos/core/beebeeb-core/src/bin/generate_test_vectors.rs`. Its plaintext
// is a placeholder byte sequence, not a real WebP — the AES-GCM wire format
// is codec-agnostic, so the image codec adds nothing to this KAT.
//
// Same two-pronged proof as share-wrap-kat.test.ts:
//  (1) Pinned KAT — web's real decryptThumbnailBlob must decrypt core's
//      frozen vector to the exact expected plaintext; a tampered ciphertext
//      must fail the GCM auth tag.
//  (2) Live cross-implementation — the REAL compiled core code (via the
//      committed beebeeb-wasm build) encrypts/decrypts against web's REAL
//      production encryptThumbnailBlob/decryptThumbnailBlob, in both
//      directions, using whichever nonce each side actually produced.

// Pinned vector: repos/core/test-vectors/vectors.json → "thumbnail_encrypt".
const FILE_KEY_HEX = 'c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3'
const NONCE_HEX = 'a38f61c267c45539d71f941d'
const CIPHERTEXT_HEX =
  'ed73ba72618da058fbbb948ef9cf749a09b7813bfe2f1f95f72fb54414282ea1cbbb2f0bfb8ed1e183b9514a85a48f56646a99bec4e09a6161e6931fe2cc20aeb3c5598a80c6604271479fb5b6991a2aa0da50eaa363b779797d14059ce402ff07ceae7c72718f4f85cef76fabacb5f95776a178e2f85174fd792104ccaad6bbe8dfb1cae1d35ed7b652e28f40094c7f'
const PLAINTEXT_HEX = Array.from({ length: 128 }, (_, i) => i.toString(16).padStart(2, '0')).join('')

function hexToBytes(hex: string): Uint8Array {
  const out = new Uint8Array(hex.length / 2)
  for (let i = 0; i < out.length; i++) out[i] = parseInt(hex.slice(i * 2, i * 2 + 2), 16)
  return out
}

function toHex(bytes: Uint8Array): string {
  return [...bytes].map((b) => b.toString(16).padStart(2, '0')).join('')
}

beforeAll(() => {
  const wasmPath = fileURLToPath(
    new URL('../packages/beebeeb-wasm/beebeeb_wasm_bg.wasm', import.meta.url),
  )
  initSync({ module: readFileSync(wasmPath) })
})

describe('thumbnail-encryption cross-client KAT (web thumbnail.ts == core)', () => {
  test('(1) decryptThumbnailBlob decrypts the pinned core vector to the exact expected plaintext', async () => {
    const fileKey = hexToBytes(FILE_KEY_HEX)
    const encrypted = hexToBytes(NONCE_HEX + CIPHERTEXT_HEX)

    const decrypted = await decryptThumbnailBlob(encrypted, fileKey)
    expect(toHex(new Uint8Array(decrypted))).toBe(PLAINTEXT_HEX)
  })

  test('(1b) a tampered ciphertext byte fails GCM authentication', async () => {
    const fileKey = hexToBytes(FILE_KEY_HEX)
    const encrypted = hexToBytes(NONCE_HEX + CIPHERTEXT_HEX)
    // Flip one bit well inside the ciphertext (leave the 12-byte nonce untouched).
    encrypted[20] ^= 0x01

    await expect(decryptThumbnailBlob(encrypted, fileKey)).rejects.toThrow()
  })

  test('(2a) core (via WASM) encrypts -> web decryptThumbnailBlob decrypts to the same plaintext', async () => {
    const fileKey = hexToBytes(FILE_KEY_HEX)
    const plaintext = hexToBytes(PLAINTEXT_HEX)

    const encrypted = encrypt_chunk(fileKey, plaintext) as {
      nonce: Uint8Array
      ciphertext: Uint8Array
    }
    const wire = new Uint8Array(encrypted.nonce.length + encrypted.ciphertext.length)
    wire.set(encrypted.nonce, 0)
    wire.set(encrypted.ciphertext, encrypted.nonce.length)

    const decrypted = await decryptThumbnailBlob(wire, fileKey)
    expect(toHex(new Uint8Array(decrypted))).toBe(PLAINTEXT_HEX)
  })

  test('(2b) web encryptThumbnailBlob encrypts -> core (via WASM) decrypts to the same plaintext', async () => {
    const fileKey = hexToBytes(FILE_KEY_HEX)
    const plaintext = hexToBytes(PLAINTEXT_HEX)
    const blob = new Blob([plaintext.buffer as ArrayBuffer])

    const wire = await encryptThumbnailBlob(blob, fileKey)
    const nonce = wire.slice(0, 12)
    const ciphertext = wire.slice(12)

    const decrypted = decrypt_chunk(fileKey, nonce, ciphertext) as Uint8Array
    expect(toHex(new Uint8Array(decrypted))).toBe(PLAINTEXT_HEX)
  })

  test('(2c) web encrypt -> web decrypt roundtrip (regression guard)', async () => {
    const fileKey = hexToBytes(FILE_KEY_HEX)
    const plaintext = hexToBytes(PLAINTEXT_HEX)
    const blob = new Blob([plaintext.buffer as ArrayBuffer])

    const wire = await encryptThumbnailBlob(blob, fileKey)
    const decrypted = await decryptThumbnailBlob(wire, fileKey)
    expect(toHex(new Uint8Array(decrypted))).toBe(PLAINTEXT_HEX)
  })
})
