/**
 * New-document templates (task 1567 TemplatesGallery) — Blank, Letter,
 * Invoice, Meeting notes, Report, matching design/office-editor.html's
 * templates screen ("five choices, not fifty").
 *
 * Per the brief ("ship small template files... generated by the engine or
 * hand-made, in-repo, no network"): every template is generated BY THE
 * ENGINE ITSELF, at the moment "New document" is clicked — a short sequence
 * of real `.uno:` dispatches against a freshly-opened blank document (heading
 * styles, placeholder body text, an inserted table for Invoice). Nothing is
 * fetched from anywhere; there is no pre-baked .docx blob to keep in sync
 * with engine version drift, and the content is genuinely editable from the
 * first keystroke (not a flattened image of a "template").
 *
 * The metadata table itself (id/label/description) is pure and unit-tested;
 * `applyTemplate` (below) is the impure half that actually calls the bridge —
 * covered instead by the office e2e suite, since it needs the real engine.
 */

import type { OfficeBridge } from './bb-office-bridge'

export interface TemplateDef {
  id: 'blank' | 'letter' | 'invoice' | 'meeting-notes' | 'report'
  label: string
  description: string
}

export const TEMPLATE_DEFS: TemplateDef[] = [
  { id: 'blank', label: 'Blank', description: 'Start from nothing' },
  { id: 'letter', label: 'Letter', description: 'Formal letter, address block' },
  { id: 'invoice', label: 'Invoice', description: 'Line items, tax, totals' },
  { id: 'meeting-notes', label: 'Meeting notes', description: 'Agenda, notes, action items' },
  { id: 'report', label: 'Report', description: 'Title page, sections, summary' },
]

async function paragraphStyle(bridge: OfficeBridge, style: string) {
  await bridge.dispatch('.uno:StyleApply', [
    { name: 'Style', value: style },
    { name: 'FamilyName', value: 'ParagraphStyles' },
  ])
}
async function text(bridge: OfficeBridge, value: string) {
  await bridge.dispatch('.uno:InsertText', [{ name: 'Text', value }])
}
async function newPara(bridge: OfficeBridge) {
  await bridge.dispatch('.uno:InsertPara')
}

/** Builds the starter content for `templateId` into the CURRENTLY open
 *  (already-blank) Writer document. Caller is responsible for
 *  `newDocument('writer')` first. */
export async function applyTemplate(bridge: OfficeBridge, templateId: TemplateDef['id']): Promise<void> {
  switch (templateId) {
    case 'blank':
      return
    case 'letter':
      await paragraphStyle(bridge, 'Default Paragraph Style')
      await text(bridge, 'Your Name')
      await newPara(bridge)
      await text(bridge, 'Your Address')
      await newPara(bridge)
      await newPara(bridge)
      await text(bridge, new Date().toLocaleDateString())
      await newPara(bridge)
      await newPara(bridge)
      await text(bridge, 'Dear [Recipient],')
      await newPara(bridge)
      await newPara(bridge)
      await text(bridge, 'Sincerely,')
      await newPara(bridge)
      await text(bridge, 'Your Name')
      return
    case 'invoice':
      await paragraphStyle(bridge, 'Heading 1')
      await text(bridge, 'Invoice')
      await newPara(bridge)
      await paragraphStyle(bridge, 'Default Paragraph Style')
      await text(bridge, 'Bill to: [Client name]        Invoice #: 0001        Date: ' + new Date().toLocaleDateString())
      await newPara(bridge)
      await newPara(bridge)
      await bridge.dispatch('.uno:InsertTable', [
        { name: 'Columns', value: 4 },
        { name: 'Rows', value: 4 },
      ])
      return
    case 'meeting-notes':
      await paragraphStyle(bridge, 'Heading 1')
      await text(bridge, 'Meeting notes')
      await newPara(bridge)
      await paragraphStyle(bridge, 'Heading 2')
      await text(bridge, 'Attendees')
      await newPara(bridge)
      await paragraphStyle(bridge, 'Heading 2')
      await text(bridge, 'Agenda')
      await newPara(bridge)
      await paragraphStyle(bridge, 'Heading 2')
      await text(bridge, 'Action items')
      return
    case 'report':
      await paragraphStyle(bridge, 'Heading 1')
      await text(bridge, 'Report title')
      await newPara(bridge)
      await paragraphStyle(bridge, 'Default Paragraph Style')
      await text(bridge, 'Prepared by · ' + new Date().toLocaleDateString())
      await newPara(bridge)
      await newPara(bridge)
      await paragraphStyle(bridge, 'Heading 2')
      await text(bridge, 'Summary')
      await newPara(bridge)
      await paragraphStyle(bridge, 'Heading 2')
      await text(bridge, 'Details')
      return
  }
}
