/**
 * CLI web-auth page — route: /cli-auth?nonce=<uuid>&port=<port>
 *
 * Lets an authenticated browser session authorize the Beebeeb CLI without
 * typing a password into a terminal. UX mirrors `gh auth login --web`.
 *
 * Flow:
 *   1. `bb login --browser` starts a local HTTP server on a random port.
 *   2. It opens https://app.beebeeb.io/cli-auth?nonce=<uuid>&port=<port>.
 *   3. This page checks the params, shows the auth prompt to the signed-in
 *      user, and on "Authorize" POSTs the session token + master key (b64)
 *      to http://localhost:<port>/callback.
 *   4. The CLI receives the callback, stores the credentials, and shuts the
 *      local server down.
 *
 * Security notes:
 * - The nonce is generated by the CLI and validated for UUID format here.
 * - The port must be in the unprivileged range (1024-65535).
 * - Modern browsers allow fetch() to http://localhost from HTTPS pages
 *   as an exception to mixed-content rules — this is intentional and is
 *   the same mechanism used by GitHub CLI, Vercel CLI, etc.
 * - The master key is only sent over the loopback interface to a port
 *   that the user's own CLI process opened.
 */

import { useState, useEffect } from 'react'
import { useSearchParams, useNavigate } from 'react-router-dom'
import { BBButton } from '../components/bb-button'
import { BBLogo } from '../components/bb-logo'
import { Icon } from '../components/icons'
import { useAuth } from '../lib/auth-context'
import { useKeys } from '../lib/key-context'
import { getToken } from '../lib/api'
import { toBase64 } from '../lib/crypto'

// ─── Param validation ─────────────────────────────────────────────────────────

const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i

function parsePort(raw: string | null): number | null {
  if (!raw) return null
  const n = parseInt(raw, 10)
  if (isNaN(n) || n < 1024 || n > 65535) return null
  return n
}

function parseNonce(raw: string | null): string | null {
  if (!raw) return null
  if (!UUID_RE.test(raw)) return null
  return raw
}

// ─── States ───────────────────────────────────────────────────────────────────

type PageState =
  | { kind: 'invalid_params' }
  | { kind: 'prompt' }
  | { kind: 'authorizing' }
  | { kind: 'success' }
  | { kind: 'error'; message: string }

// ─── Page ─────────────────────────────────────────────────────────────────────

export function CliAuth() {
  const [params] = useSearchParams()
  const navigate = useNavigate()
  const { user } = useAuth()
  const { isUnlocked, getMasterKey } = useKeys()

  const nonce = parseNonce(params.get('nonce'))
  const port = parsePort(params.get('port'))

  const [state, setState] = useState<PageState>(
    nonce && port ? { kind: 'prompt' } : { kind: 'invalid_params' }
  )

  // Redirect to login if not authenticated
  useEffect(() => {
    if (!user) {
      const returnTo = encodeURIComponent(window.location.pathname + window.location.search)
      navigate(`/login?next=${returnTo}`, { replace: true })
    }
  }, [user, navigate])

  async function handleAuthorize() {
    if (!user || !nonce || !port || !isUnlocked) return
    setState({ kind: 'authorizing' })

    try {
      const sessionToken = getToken()
      if (!sessionToken) throw new Error('No active session — please sign in again.')

      const masterKey = getMasterKey()
      const masterKeyB64 = toBase64(masterKey)

      // POST to the CLI's local HTTP server.
      // Browsers allow http://localhost fetch from HTTPS as a mixed-content
      // exception (same mechanism as gh cli, vercel cli, stripe cli, etc.).
      const res = await fetch(`http://localhost:${port}/callback`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          nonce,
          session_token: sessionToken,
          master_key_b64: masterKeyB64,
          email: user.email,
        }),
        // Short timeout — if the CLI isn't running, fail fast
        signal: AbortSignal.timeout(5000),
      })

      if (!res.ok) {
        const body = await res.text().catch(() => 'No response body')
        throw new Error(`CLI returned ${res.status}: ${body}`)
      }

      setState({ kind: 'success' })
    } catch (err) {
      const msg =
        err instanceof Error
          ? err.message.includes('Failed to fetch') || err.message.includes('NetworkError') || err.message.includes('Load failed')
            ? `Could not reach the CLI on port ${port}. Make sure \`bb login --browser\` is still running and try again.`
            : err.message
          : 'Authorization failed. Try running `bb login --browser` again.'
      setState({ kind: 'error', message: msg })
    }
  }

  // Loading while auth state settles
  if (!user) return null

  return (
    <div className="min-h-screen flex items-center justify-center bg-paper-2">
      <div className="w-full max-w-[420px] mx-4">
        {/* Logo */}
        <div className="text-center mb-8">
          <BBLogo size={14} />
        </div>

        <div className="rounded-xl border border-line bg-paper shadow-3 overflow-hidden">
          {/* ── Invalid params ── */}
          {state.kind === 'invalid_params' && (
            <>
              <div className="px-6 py-4 border-b border-line flex items-center gap-2.5">
                <Icon name="x" size={14} className="text-red" />
                <span className="text-sm font-semibold text-ink">Invalid request</span>
              </div>
              <div className="p-6">
                <p className="text-sm text-ink-3 leading-relaxed">
                  This authorization link is missing required parameters or has an invalid format.
                  Please run <code className="font-mono text-xs bg-paper-2 border border-line px-1.5 py-0.5 rounded">bb login --browser</code> again to get a fresh link.
                </p>
                <div className="mt-4 text-[12px] text-ink-4 font-mono">
                  <div>nonce: {params.get('nonce') ?? '(missing)'}</div>
                  <div>port: {params.get('port') ?? '(missing)'}</div>
                </div>
              </div>
            </>
          )}

          {/* ── Auth prompt ── */}
          {state.kind === 'prompt' && (
            <>
              <div className="px-6 py-4 border-b border-line flex items-center gap-2.5">
                <Icon name="shield" size={14} className="text-amber-deep" />
                <span className="text-sm font-semibold text-ink">Authorize Beebeeb CLI</span>
              </div>
              <div className="p-6">
                {/* User identity */}
                <div className="flex items-center gap-3 mb-5 p-3 rounded-lg bg-paper-2 border border-line">
                  <div className="w-9 h-9 rounded-full bg-amber-bg text-amber-deep flex items-center justify-center text-[13px] font-bold shrink-0">
                    {user.email.charAt(0).toUpperCase()}
                  </div>
                  <div className="flex-1 min-w-0">
                    <div className="text-[13px] font-medium text-ink truncate">{user.email}</div>
                    <div className="text-[11px] text-ink-3">Signed in · Vault unlocked</div>
                  </div>
                  <Icon name="check" size={13} className="text-green shrink-0" />
                </div>

                {/* What's being authorized */}
                <div className="mb-5">
                  <p className="text-sm text-ink-2 leading-relaxed mb-3">
                    The <span className="font-medium text-ink">Beebeeb CLI</span> running on this machine is requesting access to your account.
                  </p>
                  <div className="text-[12px] text-ink-3 space-y-1.5">
                    <div className="flex items-center gap-2">
                      <Icon name="check" size={11} className="text-green shrink-0" />
                      Read and upload your encrypted files
                    </div>
                    <div className="flex items-center gap-2">
                      <Icon name="check" size={11} className="text-green shrink-0" />
                      Access your master encryption key locally
                    </div>
                    <div className="flex items-center gap-2">
                      <Icon name="check" size={11} className="text-green shrink-0" />
                      Stay signed in until you run <code className="font-mono text-[11px]">bb logout</code>
                    </div>
                  </div>
                </div>

                {/* Port verification strip */}
                <div className="mb-5 p-3 rounded-lg border border-line-2 bg-paper-2 text-[11.5px] text-ink-3">
                  <div className="flex items-center gap-1.5 font-mono">
                    <Icon name="link" size={10} className="text-ink-4 shrink-0" />
                    <span className="text-ink-4">Callback: </span>
                    <span className="text-ink-2">http://localhost:<span className="text-amber-deep font-semibold">{port}</span>/callback</span>
                  </div>
                  <div className="mt-1 text-[10.5px] text-ink-4 font-mono truncate">
                    Nonce: {nonce}
                  </div>
                </div>

                {/* Vault lock warning */}
                {!isUnlocked && (
                  <div className="mb-4 px-3 py-2.5 bg-amber-bg border border-amber/30 rounded-lg text-[12px] text-ink-2">
                    <Icon name="lock" size={11} className="text-amber-deep inline mr-1.5" />
                    Your vault is locked. Unlock it to send the encryption key to the CLI.
                  </div>
                )}

                <BBButton
                  variant="amber"
                  size="lg"
                  className="w-full justify-center gap-2"
                  onClick={handleAuthorize}
                  disabled={!isUnlocked}
                >
                  <Icon name="check" size={14} />
                  Authorize CLI access
                </BBButton>

                <p className="mt-3 text-center text-[11px] text-ink-4">
                  This sends your session token and master key to the CLI process running on your machine.
                </p>
              </div>
            </>
          )}

          {/* ── Authorizing ── */}
          {state.kind === 'authorizing' && (
            <div className="flex flex-col items-center gap-3 px-6 py-12">
              <svg className="animate-spin h-6 w-6 text-amber" viewBox="0 0 24 24" fill="none">
                <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="3" />
                <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z" />
              </svg>
              <span className="text-sm text-ink-3">Sending credentials to CLI…</span>
            </div>
          )}

          {/* ── Success ── */}
          {state.kind === 'success' && (
            <>
              <div className="px-6 py-4 border-b border-line flex items-center gap-2.5">
                <Icon name="check" size={14} className="text-green" />
                <span className="text-sm font-semibold text-ink">CLI authorized</span>
              </div>
              <div className="p-6 text-center">
                <div className="w-14 h-14 mx-auto mb-4 rounded-full bg-green/10 flex items-center justify-center">
                  <Icon name="check" size={24} className="text-green" />
                </div>
                <h2 className="text-[15px] font-semibold text-ink mb-2">You're all set</h2>
                <p className="text-sm text-ink-3 leading-relaxed">
                  The CLI has been authorized as <span className="font-medium text-ink">{user.email}</span>.
                  You can close this tab and return to your terminal.
                </p>
                <p className="mt-4 font-mono text-[11px] text-ink-4">
                  You can revoke CLI access at any time via Settings → Security → Active sessions.
                </p>
              </div>
            </>
          )}

          {/* ── Error ── */}
          {state.kind === 'error' && (
            <>
              <div className="px-6 py-4 border-b border-line flex items-center gap-2.5">
                <Icon name="x" size={14} className="text-red" />
                <span className="text-sm font-semibold text-ink">Authorization failed</span>
              </div>
              <div className="p-6">
                <p className="text-sm text-ink-2 leading-relaxed mb-4">{state.message}</p>
                <BBButton
                  variant="default"
                  size="md"
                  className="w-full justify-center"
                  onClick={() => setState({ kind: 'prompt' })}
                >
                  Try again
                </BBButton>
              </div>
            </>
          )}

          {/* Footer */}
          <div className="px-6 py-3 bg-paper-2 border-t border-line">
            <div className="flex items-center justify-center gap-1.5 text-[11px] text-ink-3">
              <Icon name="shield" size={11} className="text-amber-deep" />
              Credentials stay on this machine — beebeeb.io never sees them
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}
