#!/usr/bin/env python3
"""
Regenerate the blank Office documents behind Drive's "+ New" menu (task 1582).

Run with LibreOffice's OWN bundled Python (it ships the `uno` module):

    /Applications/LibreOffice.app/Contents/Resources/python \
        scripts/generate-blank-office-files.py

Why fixtures produced by LibreOffice itself (not hand-written XML, not the
browser engine): the files are then byte-for-byte what LibreOffice's own
"File > New" + "Save as" writes — the same filters our WASM fork runs — so
they are valid for our editor AND for desktop Word/Excel/PowerPoint and
LibreOffice. Generating them in the browser would mean booting the ~55 MB
engine inside Drive just to make an empty file, and would couple "create a
file" to the Labs-gated editor bundle. See the 1582 task file for the full
decision.

Privacy: a THROWAWAY user profile (-env:UserInstallation) is used, so no
author name, recent-files list or machine-specific setting of whoever runs
this ends up in the committed files. `test/1582-blank-documents.test.ts`
re-checks the OOXML structure and that docProps carry no author.
"""

import base64
import os
import shutil
import subprocess
import sys
import tempfile
import time

import uno
from com.sun.star.beans import PropertyValue

SOFFICE = "/Applications/LibreOffice.app/Contents/MacOS/soffice"
OUT_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "src", "lib", "office", "blank")
# The bytes the app actually ships: a base64 module, lazy-imported only when
# someone creates a document (no runtime fetch, no CSP data:/connect-src
# question, and the unit test validates exactly these bytes).
TS_OUT = os.path.join(OUT_DIR, "..", "blank-documents.generated.ts")

# (factory, output file, export filter name)
DOCS = [
    ("swriter", "blank.docx", "MS Word 2007 XML"),
    ("scalc", "blank.xlsx", "Calc MS Excel 2007 XML"),
    ("simpress", "blank.pptx", "Impress MS PowerPoint 2007 XML"),
    ("swriter", "blank.odt", "writer8"),
    ("scalc", "blank.ods", "calc8"),
    ("simpress", "blank.odp", "impress8"),
]


def prop(name, value):
    p = PropertyValue()
    p.Name = name
    p.Value = value
    return p


def write_ts_module():
    lines = [
        "// GENERATED by scripts/generate-blank-office-files.py — do not edit.",
        "// Blank documents written by LibreOffice itself (task 1582); the .docx/",
        "// .xlsx/... files next to this module in ./blank/ are the same bytes.",
        "// test/1582-blank-documents.test.ts fails if the two ever drift apart.",
        "",
        "export const BLANK_DOCUMENTS_BASE64: Record<string, string> = {",
    ]
    for _, name, _ in DOCS:
        ext = name.split(".")[-1]
        with open(os.path.join(OUT_DIR, name), "rb") as fh:
            b64 = base64.b64encode(fh.read()).decode("ascii")
        lines.append("  %s: '%s'," % (ext, b64))
    lines.append("}")
    with open(os.path.abspath(TS_OUT), "w") as fh:
        fh.write("\n".join(lines) + "\n")
    print("wrote %s" % os.path.abspath(TS_OUT))


def main():
    profile = tempfile.mkdtemp(prefix="bb-lo-profile-")
    pipe = "bb_blank_%d" % os.getpid()
    proc = subprocess.Popen([
        SOFFICE,
        "-env:UserInstallation=file://" + profile,
        "--headless", "--invisible", "--nologo", "--norestore", "--nodefault",
        "--accept=pipe,name=%s;urp;" % pipe,
    ])
    try:
        local = uno.getComponentContext()
        resolver = local.ServiceManager.createInstanceWithContext("com.sun.star.bridge.UnoUrlResolver", local)
        ctx = None
        for _ in range(120):
            try:
                ctx = resolver.resolve("uno:pipe,name=%s;urp;StarOffice.ComponentContext" % pipe)
                break
            except Exception:
                time.sleep(0.5)
        if ctx is None:
            print("could not connect to soffice", file=sys.stderr)
            return 1
        desktop = ctx.ServiceManager.createInstanceWithContext("com.sun.star.frame.Desktop", ctx)
        os.makedirs(OUT_DIR, exist_ok=True)
        for factory, name, filt in DOCS:
            doc = desktop.loadComponentFromURL("private:factory/" + factory, "_blank", 0, (prop("Hidden", True),))
            # No author / no template stamp from whoever regenerates this.
            props = doc.getDocumentProperties()
            props.Author = ""
            props.ModifiedBy = ""
            target = os.path.abspath(os.path.join(OUT_DIR, name))
            doc.storeToURL(uno.systemPathToFileUrl(target), (prop("FilterName", filt),))
            doc.close(True)
            print("wrote %s (%d bytes)" % (target, os.path.getsize(target)))
        write_ts_module()
        try:
            desktop.terminate()
        except Exception:
            pass  # the bridge drops as soffice exits — expected
        return 0
    finally:
        try:
            proc.wait(timeout=30)
        except subprocess.TimeoutExpired:
            proc.kill()  # our own recorded child, never a name match
        shutil.rmtree(profile, ignore_errors=True)


if __name__ == "__main__":
    sys.exit(main())
